### ISSUE TITLE
cmd error? this may just be me, can anyone help? I am new to this as well

### ISSUE THREAD

**Issue by DieselJS** [xjmdoo/discord-snipe-bot#1]
so when i do npm start it says this. 
![image](https://user-images.githubusercontent.com/44411085/48579269-e1fe7400-e913-11e8-9a72-a36a7c53310b.png)

**Comment by xjmdoo** [comment]
@DieselGaming , you can start the bot with `node index.js`, there's no start script defined for it yet. Also, this project is a work in progress, there's still a lot of stuff that needs to be done before it can function as a real snipe bot. I probably should have added that to the Readme. Please feel free to contribute to the project by opening pull requests.
